name: Build PlatformIO Project
 
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - name: Install PlatformIO
      run: python -m pip install -U platformio
 
    - name: Build Project
      run: platformio run
